import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400"],
});

export const metadata = {
  title: "Leo's Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  console.log("Root");
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
